### ISSUE TITLE
LTV issues

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-lendingtree#14]
While posting LTV data to the integration, it is not acknowledged by the unified integration. Please see here: 

https://next.leadconduit.com/events/54a1b486a36b4a5313263c61 - Under Karalyn Test account.
Note: This is fake data from LT themselves sample XMLs, not real data. 

...<PresentLTV>66.6674</PresentLTV> <ProposedLTV>66.6674</ProposedLTV> ...

**Comment by zalary** [comment]
is this a problem for any existing integrations or can we close for now?

**Comment by kcaponeAP** [comment]
This can be closed. Will reopen if needed.
