### ISSUE TITLE
Local Loan Officer Program

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-lendingtree#18]
Create instructions for dev to create Local Lending Tree Officer Program

**Comment by kcaponeAP** [comment]
These are direct notes from Aru: @alexkwolfe Would you like to review/discuss? Falls in line with the pricing engine stuff we discussed yesterday.

LT generates Lead -> posts to CRM/PricingEngine(PE)1 -> CRM/PE matches the lead zip with Loan Officer(LO) in their system -> CRM/PR respond to LT with the LO information2 -> LT displays LO information to consumer on LT Portal3

1.       LT posts lead REQUEST to CRM/PricingEngine – this will be Purchase Longform or ShortForm lead XML as documented in http://screencast.com/t/J894ysYAY9

2.       This is Offer/LO RESPONSE received at LT endpoint – example #3 in documentation - http://screencast.com/t/J894ysYAY9

a.       <LoanApplicationID>10008967345</LoanApplicationID>  in RESPONSE maps to <TrackingNumber>102345679</TrackingNumber> in REQUEST

b.      <LenderID>9999999</LenderID> in RESPONSE maps to <TrusteePartnerID>123456</TrusteePartnerID> in REQUEST

3.       LT portal with LO information - http://screencast.com/t/lgNvWkObzr

**Comment by alexkwolfe** [comment]
It sounds like this leaves LeadConduit out of the process for responding back to LendingTree with the local loan officer information. Do you concur?

**Comment by kcaponeAP** [comment]
I think it was under Maya's assumption that we would handle the response, but I can see that it happens at the CRM level. I'll speak with Hansen and deliver the news to Maya.

**Comment by alexkwolfe** [comment]
We can handle the response, but we'd need a way to get the pricing information and loan officer information into LeadConduit somehow. Some external system would have to provide all that.

**Comment by kcaponeAP** [comment]
You are sort of saying two things tho. I understand we can do the response, but do we want to do that? What I'm looking for is some idea of whether or not we want to create this for her (and other clients) or leave it up to the CRM. And is this professional services or part of the integration.

**Comment by alexkwolfe** [comment]
I don't think we should do it unless there is both a reason and the technical capability to do it. You'll have to answer whether there is a reason. Once we know that, then we can investigate whether we have the technical capability to do it given the systems we are working with.

**Comment by kcaponeAP** [comment]
10-4 to that. Tyvm.

**Comment by kcaponeAP** [comment]
This can be closed. We are going to instruct Maya that Velocify is suited to handle this.
