### ISSUE TITLE
Missing null check causes exception

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-lendingtree#22]
There is a missing null check in [unified.coffee](https://github.com/activeprospect/leadconduit-integration-lendingtree/blob/6b8da5002360d3966ed8d4d1f0b0d0a45ed2ced9/src/unified.coffee#L23). This caused [an error in production](https://app.honeybadger.io/projects/2160/faults/10831882#notice-summary).

**Comment by zalary** [comment]
I think this is caused by line 26 where SelfCreditRating is missing a null check
