### ISSUE TITLE
Parse LoanReason fails when there is more than one reason

### ISSUE THREAD

**Issue by zalary** [activeprospect/leadconduit-integration-lendingtree#23]
https://app.honeybadger.io/projects/2160/faults/12389709#notice-summary

**Comment by zalary** [comment]
we should handle when we are given more than one loan reason, but the question is 'how' to handle it.  should we convert multiple reasons into a single, comma-separated string?  or if we have more than one reason, should we loop through and make a loan_reason1 and a loan_reason2?   

It looks like this field is lendingtree specific and we don't pass it along to anyone, so maybe this is less important, but how we parse it will affect how easy/hard it is to make rules on this field in the future

For example, we convert 'GREENLOAN' into 'green loan' and 'CCREFI' into 'refinance credit card(s)' and it seems like that kind of parsing is harder to maintain when there are multiple values.

any thoughts or insight would be appreciated.

**Comment by alexkwolfe** [comment]
If multiple reasons are present, you can provide an array instead of a string in that field. Then the user can use the [includes operator](https://github.com/activeprospect/leadconduit-rules/blob/master/src/operators/includes.coffee).

**Comment by zalary** [comment]
resolved with PR #24
