### ISSUE TITLE
Mask SSNs in UI

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-lendingtree#25]
I noticed that SSNs are viewable in LT leads. My question is: was masking these in the XML intended behaviour? I also see that the integration is not picking up this information. I will open a separate issue for that.

https://next.leadconduit.com/events/55560d01912e50770334e6d7

**Comment by cgrayson** [comment]
So many questions…

1. Why did you open the same issue [twice](https://github.com/activeprospect/leadconduit-integration-lendingtree/issues/26)? 
2. Why did you open it on LendingTree and say "LT" but link to a LowerMyBills lead? 
3. Which SSNs are do you mean? If you meant the raw data as posted in, before it gets put into the LeadConduit `ssn` field, then I'm less sure that's supposed to get masked

**Comment by kcaponeAP** [comment]
Ah. Strange, I must have double clicked. I'll clear this up and move this over to LMB.

**Comment by kcaponeAP** [comment]
(I know why I opened it under the wrong repo. The logo is so tiny and the same color as LT)
