### ISSUE TITLE
missing helper function in 'unified' integration

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-integration-lendingtree#39]
The `unified` integration is still trying to use a [helper function that was removed in July, 2015](https://github.com/activeprospect/leadconduit-integration-lendingtree/commit/0f76c331dd45372a174217b6265e10ae6144bb46#diff-07060f427d194bb8909bc212c2487e1f). This causes inbound leads to error out with the message:

> Unhandled error: Object #\<Object> has no method 'integer'

**Comment by ros3bud** [comment]
solved in 1.6.3
