### ISSUE TITLE
mortage.application.first_mortgage_balance is now mortgage.refi.loan_balance

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-lendingtree#4]
Update the inbound integration and add a test against leadconduit-fields.

**Comment by cgrayson** [comment]
This old must be out of date, as according to [the mortgage fields definition](https://github.com/activeprospect/leadconduit-fields/blob/master/fields/mortgage.json#L52), `mortgage.refi.loan_balance` is now itself deprecated, in favor of `mortgage.first_mortgage_balance`.
