### ISSUE TITLE
clean up integrations

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-integration-lendingtree#47]
The code and integrations for the various types of leads from this provider are a mess. I propose the following (note that our current `multiformat` integration automatically handles either "shortform" or "unified" format data):

1. **remove all `longform` code** - there are source and test files, but this integration has never even been listed in `index.js`, and therefore never used. 
2. **remove `shortform` from `index.js`** - the code will stay, and the `multiformat` integration already uses this when appropriate. Having this as a choice in flow configuration is extra confusion and a possible source of trouble
3. **rename `multiformat` to `mortgage`** - the current name doesn't match a LendingTree product name, and is confusingly similar to "unified". Unless there are other mortgage formats that we wouldn't build under this name (i.e., automatically handle whatever format it gets), this is enough to differentiate from `personal_loan`

That would leave `unified`, `mortgage`, and `personal_loan`. Possibly even `unified` could be removed, though since it's the name of a LendingTree product, it might be worth keeping.

**Comment by ros3bud** [comment]
Fixed in 1.7.0
