### ISSUE TITLE
map MatchFee to lead.price

### ISSUE THREAD

**Issue by zalary** [activeprospect/leadconduit-integration-lendingtree#6]
per  https://github.com/activeprospect/leadconduit-integration-velocify/issues/13

**Comment by kcaponeAP** [comment]
Has this been resolved / deployed? I see that the notes reflect that there is price now listed in the docs. Tidying up old issues.

**Comment by zalary** [comment]
not sure exactly which version, but confirmed this has been in the code since mid-Dec so should be all set
